### ISSUE TITLE
What folder to use for policy files?

### ISSUE THREAD

**Issue by zendynar** [flathub/com.github.Eloston.UngoogledChromium#100]
I've installed the flatpak version of ungoogled chromium on my ubuntu 20.04 machine and it has been working like a charm. However, I need to apply a policy .json file. In deb chromium I would put it in `/etc/opt/chromium/policies/managed/`. On flatpak version I am not clear on what folder to choose. I obviously tried using `/etc/opt/chromium/`, `/etc/opt/chrome`, `/etc/chromium`, `~/.var/app/com.github.Eloston.UngoogledChromium/`, `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium/` but all without any results - the `chrome://policy` page in chromium is empty and doesn't recognize my policy.json file. I see in this repo's read me that the flattpak extensions are used, but I didn't find any documentation on how to use this as a used and what folder to use to put my file in. I also tried giving the app access to the whole disk using flatseal but no avail.

The .json file I put into policies folder is called auto-select-certificates.json, this is its content (anonymized):
```json
{
    "AutoSelectCertificateForUrls": [
            "{\"pattern\":\"[*.]XXX\",\"filter\":{\"ISSUER\":{\"CN\":\"YYYYYY\"}}}"
    ]
}
```
I am stuck now. Could you please point me into the right direction here, how can I use my policy file there?

**Comment by rany2** [comment]
You need to build this extension: https://github.com/flathub/com.github.Eloston.UngoogledChromium/tree/master/examples/policies/block-dinosaur-game

Follow instructions here: https://github.com/flathub/com.github.Eloston.UngoogledChromium#using-extension-points
