### ISSUE TITLE
Passwords not being saved

### ISSUE THREAD

**Issue by netgrims** [flathub/com.github.Eloston.UngoogledChromium#103]
I recently had to reinstall my OS (Fedora 37), and also reinstalled the Ungoogled Chromium Flatpak, and copied over the user files in /home from my last install. Since the new installation, passwords don't get saved into the password manager anymore. I also can't get KeePassXC to work with it, so now I need to copy over passwords every time. 

I tried turning off "Clear cookies and browser data when you close all windows", but that didn't change anything.

It doesn't work when manually adding passwords into the password manager either.

**Comment by rany2** [comment]
> I recently had to reinstall my OS (Fedora 37), and also reinstalled the Ungoogled Chromium Flatpak, and copied over the user files in /home from my last install. Since the new installation, passwords don't get saved into the password manager anymore. I also can't get KeePassXC to work with it, so now I need to copy over passwords every time.

Yes, that's I think expected. By default, Chrome expects that it could encrypt the password storage database using the GNOME keyring. If you copied your user data, then it is assuming that it has the old keyring and that caused something to get broked somewhere.

**Comment by netgrims** [comment]
Oh, right, I see. That makes sense. Any idea on how I could fix this without deleting all my user data? Is there a specific directory I can remove?
