### ISSUE TITLE
HEVC / x265 support

### ISSUE THREAD

**Issue by guria9** [flathub/com.github.Eloston.UngoogledChromium#105]
### Description

add hevc support 

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

HEVC / x265 support missing
### Possible solutions

https://github.com/search?q=repo%3AAlex313031%2Fthorium+hevc&type=commits

https://github.com/Alex313031/thorium/blob/51dbe0c8af8bcc779beef2c4523c1537762c49a4/other/add-hevc-ffmpeg-decoder-parser.patch#L4

https://github.com/Alex313031/thorium/tree/main/src/third_party/ffmpeg/libavcodec
https://github.com/Alex313031/thorium/blob/main/src/third_party/ffmpeg/libavcodec/hevc.h

>I'm willing to implement this feature myself

sadly im involved in other projects so much that my job etc already suffer from it. 
it would not come soon or could i guaranty it would come for sure.

### Alternatives

use Microsoft edge, hope it triggers someone :smile:

**Comment by rany2** [comment]
Bring this request to [upstream](https://github.com/eloston/ungoogled-chromium), this is beyond the scope of this package.
