### ISSUE TITLE
Ungoogled-chromium Flatpak has no Vulkan

### ISSUE THREAD

**Issue by Flashwalker** [flathub/com.github.Eloston.UngoogledChromium#110]
### OS/Platform

Debian, Ubuntu, and derivatives

### Installed

Flatpak

### Version

112, 113

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [X] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

Ungoogled-chromium Flatpak has no Vulkan enabled

### How to Reproduce?

1. Run:
```bash
export __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PW_PRIME_RENDER_OFFLOAD=1
flatpak run --env=__NV_PRIME_RENDER_OFFLOAD=1 --env=__GLX_VENDOR_LIBRARY_NAME=nvidia --env=PW_PRIME_RENDER_OFFLOAD=1 \
    --branch=stable \
    --arch=x86_64 \
    --command=/app/bin/chromium \
    --file-forwarding \
    com.github.Eloston.UngoogledChromium \
    @@u \
        --enable-gpu-rasterization \
        --enable-accelerated-2d-canvas \
        --enable-accelerated-video-decode \
        --ignore-gpu-blocklist \
        --enable-unsafe-webgpu \
        --enable-zero-copy \
        --enable-features=CanvasOopRasterization,EnableDrDc,RawDraw,UseSkiaRenderer,Vulkan \
        --user-data-dir=/tmp/unchrfltmp \
        --custom-ntp=chrome://gpu \
        "$@" \
    @@
```

### Actual behaviour

Vulkan Disabled

### Expected behaviour

Vulkan Enabled

### Relevant log output

```sh
F: Not sharing "/usr/lib/x86_64-linux-gnu/gtk-3.0/modules" with sandbox: Path "/usr" is reserved by Flatpak
F: Not sharing "/usr/lib/x86_64-linux-gnu/gtk-2.0/modules" with sandbox: Path "/usr" is reserved by Flatpak
Gtk-Message: 17:39:01.032: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:39:01.033: Failed to load module "appmenu-gtk-module"
Gtk-Message: 17:39:01.594: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:39:01.594: Failed to load module "appmenu-gtk-module"
[2:2:0509/173901.747329:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
Warning: vkCreateInstance: Found no drivers!
Error: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:416)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:302)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:232)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:491)

Error: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:53)
```

### Additional context

![image](https://github.com/flathub/org.chromium.Chromium/assets/2188215/b7baaffb-45db-4534-a956-4e26121845f7)

`--enable-features=VaapiVideoDecoder` - doesn't helps
`--disable-features=UseChromeOSDirectVideoDecoder` -  doesn't helps
`--use-gl=egl` - disables gpu acceleration at all

Graphics:
`inxi -G`:
```bash
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia
    v: 525.105.17
  Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 22.3.5
```

Graphics (nvidia offload):
```bash
export __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PW_PRIME_RENDER_OFFLOAD=1 
inxi -G
```

```
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia
    v: 525.105.17
  Device-3: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.105.17
```

Host driver: nvidia-525-105-17
Flatpak driver: nvidia-525-85-05 or nvidia-525-89-02

Flatpak GL installaed:
Mesa org.freedesktop.Platform.GL.default 21.3.9	21.08 flathub system
Mesa org.freedesktop.Platform.GL.default 23.0.2	22.08 flathub system
Mesa (Extra) org.freedesktop.Platform.GL.default 23.0.2	22.08-extra flathub system
nvidia-525-85-05 org.freedesktop.Platform.GL.nvidia-525-85-05 1.4 flathub system

#### Additional info:
(For **Ungoogled-chromium** v.100 Not Flatpak Not Appimage - ✅ Vulkan Enabled)

**Comment by rany2** [comment]
Did you try with non-Flatpak Ungoogled Chromium?

**Comment by Flashwalker** [comment]
> (Ungoogled-chromium Not Flatpak 100 - Vulkan Enabled)

Yeap.
If i run Ungoogled-chromium **Not** Flatpak 100 - ✅ Vulkan is Enabled

**Comment by Flashwalker** [comment]
@rany2:
> Can you test again?
-----------------------
**I updated to:**
- nvidia driver: **nvidia-driver-535** v.535.86.05
- flatpak nvidia driver:  **org.freedesktop.Platform.GL.nvidia-535-86-05** v.535.86.05
- ungoogled-chromium: **com.github.Eloston.UngoogledChromium** v.115.0.5790.110

And here is the results:

#### Flatpak UC:
```sh
flatpak run --branch=stable --arch=x86_64 -command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u \
    --enable-gpu-rasterization \
    --enable-accelerated-video-decode \
    --enable-accelerated-2d-canvas \
    --ignore-gpu-blocklist \
    --enable-unsafe-webgpu \
    --enable-zero-copy \
    --enable-features=UseSkiaRenderer,Vulkan \
    --enable-features=CanvasOopRasterization,EnableDrDc,RawDraw \
    --user-data-dir=/tmp/unchrfltmp \
    --custom-ntp=chrome://gpu \
    --no-first-run --fast --fast-start \
    --class=ungoogled-chromium-flatpak --name=ungoogled-chromium-flatpak @@
```

![2023-08-05_01-09-19-nq8](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/2188215/23f3d587-d446-44dc-ba2d-ba3681ab28ac)

```sh
[2:2:0805/011225.116528:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
Warning: vkCreateInstance: Found no drivers!
Error: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:416)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:302)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:232)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:491)

Error: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:53)

```

#### Additional info:
I'm running the **Pop!_Os 22.04** in hybrid graphics mode and the ungoggled-chromium with environment variables (for gpu offload) set to:
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only LIBVA_DRIVER_NAME=nvidia PW_PRIME_RENDER_OFFLOAD=1` to activate the nvidia gpu.  

But now i found that if i keep to set exactly the `__GLX_VENDOR_LIBRARY_NAME=nvidia` one it disables the gpu acceleration in flatpak's and appimage's **UC** at all.

**Comment by rany2** [comment]
Have a look at: https://github.com/flatpak/flatpak/issues/5131, appears to be a Flatpak issue.

**Comment by pdf** [comment]
@rany2 the linked flatpak issue appears to have been closed by the reporter as invalid (configuration error), and using the repro from that issue of running the org.freedesktop.Platform.VulkanInfo flatpak all GPUs are reported correctly here, but com.github.Eloston.UngoogledChromium refuses to see any vulkan adapters.

Are there extra runtimes or whatever that might be required for this to function?

**Comment by ninja-** [comment]
I found new information affecting all Chrome flatpaks.
Looks like org.freedesktop.Platform.GL.default is not compliant in where implicit_layer.d files are located.

See this dbg:
```
LAYER:             Searching for implicit layer manifest files
LAYER:                In following locations:
LAYER:                   /home/user2/.var/app/com.google.ChromeDev/config/vulkan/implicit_layer.d
LAYER:                   /app/etc/xdg/vulkan/implicit_layer.d
LAYER:                   /etc/xdg/vulkan/implicit_layer.d
LAYER:                   /etc/vulkan/implicit_layer.d
LAYER:                   /home/user2/.var/app/com.google.ChromeDev/data/vulkan/implicit_layer.d
LAYER:                   /app/share/vulkan/implicit_layer.d
LAYER:                   /usr/share/vulkan/implicit_layer.d
LAYER:                   /usr/share/runtime/share/vulkan/implicit_layer.d
LAYER:                   /run/host/user-share/vulkan/implicit_layer.d
LAYER:                   /run/host/share/vulkan/implicit_layer.d
```

I force it to work using:

VK_ICD_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json MESA_DEBUG=1 VK_LOADER_DEBUG=error,warn,layer,info chrome

Unfortunately, that only fixes Vulkan for X11, and even in that mode, there is no working VA-API (which now depends on Vulkan...)
I am not sure if Vulkan Wayland support for Chrome was actually merged, it could be that it wasn't...

**Comment by Flashwalker** [comment]
> VK_ICD_FILENAMES=/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json MESA_DEBUG=1 VK_LOADER_DEBUG=error,warn,layer,info chrome

Yeap, it works for me on X11, thnx!
