### ISSUE TITLE
CPU abuse and page hang after close the popup/tab

### ISSUE THREAD

**Issue by Flashwalker** [flathub/com.github.Eloston.UngoogledChromium#112]
CPU abuse and in some cases page hang after close the popup/tab
1. Run with clean profile:
```
flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chromium --file-forwarding com.github.Eloston.UngoogledChromium @@u --user-data-dir=/tmp/tmpuserdir @@
```
or:
```
ungoogled-chromium_112.0.5615.165-1.1.AppImage --user-data-dir=/tmp/tmpuserdir
```

2. Run javascript in web console or navigate to:
`https://m.vk.com/video-72495085_456240664?track_code=video_track_codevideo_824341d5sBUrutTs8qibSGrubWSHTDTgM3Ab1KmSWIyzOqQK1vORcnToiLy4wt0ZO9Q2IpIcZbZqNEqOvZdTirdlxWmimtxodYzv7PiukkdqhGFmsX4A0AVGLtHSjVWNuVX7bLmB7H9p-CoQK22scNFPpq6-`
```js
window.open('https://m.vk.com/video-72495085_456240664?track_code=video_track_codevideo_824341d5sBUrutTs8qibSGrubWSHTDTgM3Ab1KmSWIyzOqQK1vORcnToiLy4wt0ZO9Q2IpIcZbZqNEqOvZdTirdlxWmimtxodYzv7PiukkdqhGFmsX4A0AVGLtHSjVWNuVX7bLmB7H9p-CoQK22scNFPpq6-')
```
2. Close that tab

True for **Flatpak** and **Appimage** and **Portable**(tar.gz) versions (v.107 - v.113 tested).
**Deb** v.100 package ok.

**Comment by rany2** [comment]
> True for Flatpak and Appimage and Portable(tar.gz) versions (v.107 - v.113 tested).

In this case, please open an issue in Ungoogled's issue tracker BUT make sure it doesn't occur on Vanilla Chromium first.

**Comment by Flashwalker** [comment]
okay
