### ISSUE TITLE
Dark theme flags not working

### ISSUE THREAD

**Issue by amsamam** [flathub/com.github.Eloston.UngoogledChromium#118]
September 2022 I made a file ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf with the contents:
```
--force-dark-mode
--enable-features=WebUIDarkMode
```
This worked fine until a week or two ago. I am on version 114.0.5735.106 currently. It totally ignores the flags. In about://flags the only dark theme related flag I see is auto dark mode for web contents and it works but is very ugly and enables dark themes on websites those flags didn't and makes websites look different than those flags. I tried launching directly with the flags, adding to the .desktop file etc. and they are totally ignored.

**Comment by sesucc** [comment]
Bump, running version 114.0.5735.198, this is still a thing, I thought I was going insane looking up every possible option to add the options via arguments and config files for 30 minutes, none of which worked.
![flags](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/121158598/b0289fe9-5555-4099-a991-73c6fe9fb804)

**Comment by sesucc** [comment]
Bump, I can also see that in the newest version currently, the options for the flags are available in chrome://flags but are ignored by the browser.
![flags](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/121158598/9a331ca0-acfe-4a64-b350-f4c4b2adf7a9)
I can also see that version 113.0.5672.126 is the most recent I can pull via flatpak with which OP's config file still works, so somwhere between commits f32e2a65 and 7b67521f from what flatpak remote-info tells me

**Comment by rany2** [comment]
Not an issue with this Flatpak: https://github.com/ungoogled-software/ungoogled-chromium/issues/1953#issuecomment-1599184387
