### ISSUE TITLE
No available update

### ISSUE THREAD

**Issue by MikeNavy** [flathub/com.github.Eloston.UngoogledChromium#119]
Hi,

Chrome 114.0.5735.198 has been issued on Monday, June 26, 2023.
Chrome 114.0.5735.133 has been issued on Tuesday, June 13, 2023.

But, on Thursday, June 29, 2023, the version of Ungoogled-Chromium available on flathub.org is still 114.0.5735.106.

It seems a request "Update Ungoogled Chromium to 114.0.5735.133 #116" has been closed two weeks ago, but this request has failed:
![image](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/62835567/f63cb53b-72a0-4dfd-b34a-40b1fd93d8ea)

Is a new version of Ungoogled-Chromium planned? Is there a technical problem?

Regards,

MN

**Comment by networkException** [comment]
See #117

**Comment by MikeNavy** [comment]
> See #117

Hi,
This does not explain why x86_64 update is not available, the 133 build succeeded.
MN

**Comment by networkException** [comment]
I guess flathub just does that when any build fails

**Comment by rany2** [comment]
Builds should out in about 8 hours.
