### ISSUE TITLE
Download location changes with consecutive downloads

### ISSUE THREAD

**Issue by BptGrm** [flathub/com.github.Eloston.UngoogledChromium#123]
I'm running Ungoogled Chromium 115 installed via Flatpak on Ubuntu 22.04 LTS, and this was replicated on Zorin OS 16 (based on Ubuntu 20.04).

My default download folder is the standard /home/user/Downloads. I have the "Ask for location every time" option enabled.

Whenever I download several files in a row, after I specify the download location for the first file, every subsequent download location prompt opens on what I assume is a temporary location  : 

![Capture d’écran du 2023-07-21 13-54-35](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/83828302/41d2b742-161a-4647-8036-40ceb92bb18f)

This location still displays the files in the previously selected folder (i.e. at least the first downloaded file), but clicking "Download" doesn't seem to do anything, and I then have to navigate to the correct folder again.

This only seems to happen when saving to a different drive/partition than home.

**Comment by rany2** [comment]
Can't be fixed due to limitation of xdg portals.

**Comment by BptGrm** [comment]
Does that mean this is a flatpak specific issue then ? Portals won't allow/don't give permission to recall the last download location ?

**Comment by BptGrm** [comment]
Turns out this is fixable by giving extra permissions through command line or Flatseal. 
Using `--filesystem=host` solves the issue, but might be too much of a security flaw.
Do you know of any specific folder I could give access permission to that could work ?
