### ISSUE TITLE
--proxy-pac-url option is ignored

### ISSUE THREAD

**Issue by qtlin** [flathub/com.github.Eloston.UngoogledChromium#129]
### Description
 
`--proxy-pac-url=http://wpad/wpad.dat` is ignored.

### How to Reproduce?

1. verify via `curl http://wpad/wpad.dat` that proxy autoconfig data is valid.
2. launch `flatpak run com.github.Eloston.UngoogledChromium --proxy-pac-url=http://wpad/wpad.dat` 
3. open `http://ip4.me` or any other similar site that displays IP address

### Actual behaviour

Shows actual IP address.
### Expected behaviour
 
Shows proxy IP address.
### Relevant log output

Repeat same steps using `/usr/bin/chromium-browser --proxy-pac-url=http://wpad/wpad.dat` and observe that proxy IP is returned.

**Comment by rany2** [comment]
What desktop environment (DE) are you using (GNOME, KDE, etc.)?

**Comment by qtlin** [comment]
GNOME

**Comment by rany2** [comment]
@qtlin I have just read the issue you linked now, and it's related to the sandbox preventing it from resolving `wpad` bare (without a domain). What you can do is try: `flatpak run com.github.Eloston.UngoogledChromium --proxy-pac-url=http://$(host -t A wpad | awk '{print $NF; exit }')/wpad.dat`.

If that didn't work can you confirm that `curl -v http://wpad/wpad.dat` works?

**Comment by qtlin** [comment]
I am already using fully qualified host name for wpad location. And yes, curl can load wpad.dat contents and all other chromium variants including ungoogled portable work just fine. Please investigate flatpak idiosyncrasies. Thank you.

**Comment by rany2** [comment]
@qtlin Did you try the command I sent you?

**Comment by qtlin** [comment]
Your command $(....) returns fully qualified host name for my wpad.
What was the intended purpose? Replace fqdn with its IP address? I replaced manually:
`flatpak run com.github.Eloston.UngoogledChromium --proxy-pac-url=http://n.n.n.n.n/wpad.dat`
the same result, no proxy.

**Comment by rany2** [comment]
@qtlin I setup a server to test this, and indeed it seems like both flatpak chromium and ungoogled chromium do not even fetch anything from the server, I'll have a look to see if there is some build flag I could set to fix this.

**Comment by qtlin** [comment]
@rany2 any luck finding root cause?

**Comment by rany2** [comment]
@qtlin I've submitted the issue to https://github.com/flathub/org.chromium.Chromium/issues/355 so it could get more attention.
