### ISSUE TITLE
H.264 videos flickering

### ISSUE THREAD

**Issue by AlexKF98** [flathub/com.github.Eloston.UngoogledChromium#13]
I'm using Flatpak Ungoogled Chromium 88.0.4324.146 on Fedora 33 with NVIDIA proprietary drivers and many videos using the H.264 codec don't reproduce properly, with lots of flickering. I have this problem with Instagram and Twitter videos, for instance. This video is an example: https://twitter.com/nytimes/status/1357845210001195014

https://user-images.githubusercontent.com/12222211/107156166-80df7280-695b-11eb-923a-1cd0fd5a9a64.mp4

This problem doesn't happen on YouTube, which uses vp9 and av1.

**Comment by JMoerman** [comment]
This also occurs on my system with an AMD RX 570 (Mesa 20.3.4), so this issue isn't limited to systems using NVIDIA drivers.

**Comment by JMoerman** [comment]
Removing `app/com.github.Eloston.UngoogledChromium/x86_64/stable/active/files/chromium/libffmpeg.so` fixes the issue. (I guess this causes it to fall back to `runtime/com.github.Eloston.UngoogledChromium.Codecs/x86_64/stable/active/files/lib/libffmpeg.so`)

I suspect the fix from https://github.com/flathub/org.chromium.Chromium/issues/15 isn't properly ported over.

**Comment by TheEvilSkeleton** [comment]
In around 5 hours you should see an update (around two hours to build, around three hours to publish).

**Comment by TheEvilSkeleton** [comment]
Did you guys receive an update?

**Comment by AlexKF98** [comment]
The update solved it for me
