### ISSUE TITLE
When launched by clicking the icons, Ungoogled-Chromium unexpectedly closed

### ISSUE THREAD

**Issue by azarok** [flathub/com.github.Eloston.UngoogledChromium#138]
Simply click the ungoogled-chromium icon, and the app will close after a few seconds. If I run flatpak run com.github.Eloston.UngoogledChromium in the terminal, the app doesn't crash.
In order to investigate the crash, it would be good if I could get a log file.

**Comment by rany2** [comment]
Have a look at https://github.com/flathub/org.chromium.Chromium/issues/287#issuecomment-1869931000. Apparently resting the permissions in Flatseal could fix it, might be worth trying if that is relevant your case.

**Comment by azarok** [comment]
The solution suggested, resolved the problem. Many thanks
