### ISSUE TITLE
Error Deploying Prevent from Complete Updating!

### ISSUE THREAD

**Issue by sallyhaj** [flathub/com.github.Eloston.UngoogledChromium#163]
Hello all,
I am just doing a regular flatpak update, and I get this message:

```
Warning: Error deploying: renameat(deploy/runtime/com.github.Eloston.UngoogledChromium.Codecs/aarch64/tmp.q2q00U, deploy/runtime/com.github.Eloston.UngoogledChromium.Codecs/aarch64/stable): Structure needs cleaning
Installation complete.

```
Does anyone facing the same issue? what should I do?
Thank you.

**Comment by rany2** [comment]
Can you try? `flatpak repair --(user|system)` , if that doesn't work; try adding `--reinstall-all`

**Comment by rany2** [comment]
I'm closing this issue, apparently this is actually a sign of filesystem corruption and has nothing to do with flatpak. Have a look at threads similar to https://unix.stackexchange.com/questions/330742/cannot-remove-file-structure-needs-cleaning, an error like this prevents flatpak from even removing the file to clean up.

It seems like you'll need to run e2fsck offline (i.e. without it being mounted), sorry about that.

**Comment by sallyhaj** [comment]
> I'm closing this issue, apparently this is actually a sign of filesystem corruption and has nothing to do with flatpak. Have a look at threads similar to https://unix.stackexchange.com/questions/330742/cannot-remove-file-structure-needs-cleaning, an error like this prevents flatpak from even removing the file to clean up.
> 
> It seems like you'll need to run e2fsck offline (i.e. without it being mounted), sorry about that.

You're right, I've just reboot the system, and it checked the fixed the SSD corruption, and then I updated flatpak successfully.
Thank you.
