### ISSUE TITLE
Will not play protected content

### ISSUE THREAD

**Issue by djmtype** [flathub/com.github.Eloston.UngoogledChromium#167]
I can't get Spotify to play in this browser even though I have it set to do so. 

`Protected content IDs` is set to `Sites can play protected content`.

**Comment by rany2** [comment]
Did you follow https://github.com/flathub/com.github.Eloston.UngoogledChromium?tab=readme-ov-file#how-do-i-install-widevine-cdm ?

**Comment by djmtype** [comment]
Sorry, first I posted to the wrong repo, then read it's due to a ridiculous 5k license issue, so it will never be resolved.

**Comment by rany2** [comment]
It does actually work if you run that script, I have no problem running Netflix which uses WideVine.
