### ISSUE TITLE
enable_hangout_services_extension

### ISSUE THREAD

**Issue by sentriz** [flathub/com.github.Eloston.UngoogledChromium#17]
Hey, thanks for the flatpak

I noticed on my version, fresh from flathub, that google meet screensharing it not working.
ungoogled-chromium upstream has the `enable_hangout_services_extension` flag disabled
https://github.com/Eloston/ungoogled-chromium/blob/master/flags.gn#L3

where as this flatpak seems to have it enabled
https://github.com/flathub/com.github.Eloston.UngoogledChromium/blob/master/com.github.Eloston.UngoogledChromium.yaml#L220

so my question is, are these flags related to my issue? and if so, is it just because there hasn't been a new build of here pushed to flathub recently?

thanks!

**Comment by TheEvilSkeleton** [comment]
Have you tried using the normal ungoogled-chromium build before opening an issue here? I think it would be better if we can make a clear conclusion.

**Comment by sentriz** [comment]
> Have you tried using the normal ungoogled-chromium build before opening an issue here? I think it would be better if we can make a clear conclusion.

the normal build has the flag disabled so it isn't working there. someone has mad an issue
https://github.com/Eloston/ungoogled-chromium/issues/601

but on this flatpak repo, there was a commit 30 days ago to change the flag to true, unlike the normal build
https://github.com/flathub/com.github.Eloston.UngoogledChromium/commit/b9d286f0155931f2652cf72e593783ff42c64f59

so I suppose I could rephrase the question, does the latest flathub build include this commit?

**Comment by TheEvilSkeleton** [comment]
> so I suppose I could rephrase the question, does the latest flathub build include this commit?

Yes, the latest Flathub build does include the commit.
