### ISSUE TITLE
Cookies are getting cleared automatically after quit.

### ISSUE THREAD

**Issue by prateekmedia** [flathub/com.github.Eloston.UngoogledChromium#19]
I know that the option `Clear cookies and site data when you quit Chromium` have to be turned off, but still after doing that it is persisting.

When I am opening another instance of this then it has all the cookies that I want, but when I close all instances and reopen this then all cookies are gone, specially for github, I don't know of other sites.

Also this issue is not common in other sources like AppImage or binaries. +  I have done complete reinstall to confirm the issue and its still there.

**Comment by TheEvilSkeleton** [comment]
Not exactly sure how you're experiencing this. I don't have any problem with cookies here. I logged into GitHub, restarted the program and it worked fine.

**Comment by prateekmedia** [comment]
> Not exactly sure how you're experiencing this. I don't have any problem with cookies here. I logged into GitHub, restarted the program and it worked fine.
> 
> Can you run `flatpak run com.github.Eloston.UngoogledChromium//stable` and check if there are any errors?

Hmm, ok

**Comment by prateekmedia** [comment]
> Not exactly sure how you're experiencing this. I don't have any problem with cookies here. I logged into GitHub, restarted the program and it worked fine.

Also the problem is not with github itself but the whole cookies are being cleared out, (after restart) it lists github but when clicking it, it results empty page in view all cookies page.

Also chromium flatpak works fine and ungoogled chromium appImage works fine

**Comment by prateekmedia** [comment]
@TheEvilSkeleton It's fixed somehow magically.

Now the issue is to pin the app in the dock as the pin option is not coming when app is opened (it is coming for flatpak Chromium), but that will be for another issue. Thanks for your help btw.

**Comment by ramesh45345** [comment]
Probably worth mentioning I saw this issue with this flatpak a few days ago during testing, and I suspect it was this issue causing the credentials problem: https://github.com/flathub/com.brave.Browser/issues/9 . I think it got fixed by https://github.com/flathub/com.google.Chrome/pull/40 , which propagated to Brave's flatpak as well.
