### ISSUE TITLE
Passing parameters to chromium

### ISSUE THREAD

**Issue by WhyNotHugo** [flathub/com.github.Eloston.UngoogledChromium#24]
To run on Linux/Wayland, chromium needs a few flags:

```console
$ cat .config/chromium-flags.conf
--enable-features=UseOzonePlatform --ozone-platform=wayland
```

Running without these set fails:

```
$ com.github.Eloston.UngoogledChromium
[2:2:0409/114239.736999:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
```

I tried giving filesystem access to this file, but that doesn't seem to be picked up:

```console
$ grep home .local/share/flatpak/overrides/com.github.Eloston.UngoogledChromium
filesystems=home/.config/chromium-flags.conf;!home
$ com.github.Eloston.UngoogledChromium
[2:2:0409/114239.736999:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
```
```

Is there any mechanism to always pass specific flags to the browser?

**Comment by rany2** [comment]
https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/8#issuecomment-761813448

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
That's not quite working and can't figure out why:

```
$ cat ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
--enable-features=UseOzonePlatform
--ozone-platform=wayland

$ com.github.Eloston.UngoogledChromium
[2:2:0413/205128.300521:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
```

Regular chromiums runs with with those flags

**Comment by rany2** [comment]
Is this really the full file of `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf` or are you redacting things? `--enable-features` can't be specified more than once. If you want to enable multiple features they should be delimited by a comma. For example, `--enable-features=WebUIDarkMode,UseOzonePlatform`. 

If that wasn't it can you show us your overrides and run the following commands? 

```

user@localhost:~$ flatpak run --command=bash com.github.Eloston.UngoogledChromium 
user@localhost:~$ bash -x chromium 
++ get_int32_property version
++ gdbus call -e -d org.freedesktop.portal.Flatpak -o /org/freedesktop/portal/Flatpak -m org.freedesktop.DBus.Properties.Get org.freedesktop.portal.Flatpak version
++ awk 'match($0, /uint32 ([0-9]+)/, m){print m[1];}'
+ [[ 5 -lt 4 ]]
++ get_int32_property supports
++ gdbus call -e -d org.freedesktop.portal.Flatpak -o /org/freedesktop/portal/Flatpak -m org.freedesktop.DBus.Properties.Get org.freedesktop.portal.Flatpak supports
++ awk 'match($0, /uint32 ([0-9]+)/, m){print m[1];}'
+ [[ 1 -eq 0 ]]
+ [[ -f /home/user/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf ]]
+ IFS='
'
+ flags=($(grep -v '^#' "$XDG_CONFIG_HOME/chromium-flags.conf"))
++ grep -v '^#' /home/user/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
+ unset IFS
+ set -- --force-dark-mode --enable-features=WebUIDarkMode
+ flextop-init
+ export TMPDIR=/run/user/1000/app/com.github.Eloston.UngoogledChromium
+ TMPDIR=/run/user/1000/app/com.github.Eloston.UngoogledChromium
++ readlink -f chromium
+ export CHROME_WRAPPER=/home/user/chromium
+ CHROME_WRAPPER=/home/user/chromium
+ exec /app/chromium/chrome --force-dark-mode --enable-features=WebUIDarkMode
[44:44:0413/233709.934314:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
user@localhost:~$ 
```

**Comment by TheEvilSkeleton** [comment]
Can confirm the previous comment. I added the following:
```
--enable-features=WebUIDarkMode,UseOzonePlatform
--ozone-platform=wayland
--force-dark-mode
```

Everything was fine. And I was not able to reproduce it.

**Comment by WhyNotHugo** [comment]
Figured out the issue; `symlinks` don't play well here.

```console
$ cat ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
--enable-features=UseOzonePlatform
--ozone-platform=wayland

$ file ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
/home/hugo/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf: symbolic link to /home/hugo/.dotfiles/home/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
```

I keep the file as part of my dotfiles repo (to keep track of it and sync it across devices). I'm not sure how to work around the issue.

Is there an environment variable that I can use instead?

**Comment by DonQuiProgger** [comment]
> Figured out the issue; `symlinks` don't play well here.
> 
> ```
> $ cat ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
> --enable-features=UseOzonePlatform
> --ozone-platform=wayland
> 
> $ file ~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
> /home/hugo/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf: symbolic link to /home/hugo/.dotfiles/home/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf
> ```
> 
> I keep the file as part of my dotfiles repo (to keep track of it and sync it across devices). I'm not sure how to work around the issue.
> 
> Is there an environment variable that I can use instead?

Instead of doing a symlink just do a hardlink. Use ln without -s option. But keep in mind that i'm not sure what happens when you update the file with a git pull. Maybe the link gets broken.

**Comment by flightmansam** [comment]
> Can confirm the previous comment. I added the following:
> 
> ```
> --enable-features=WebUIDarkMode,UseOzonePlatform
> --ozone-platform=wayland
> --force-dark-mode
> ```
> 
> Everything was fine. And I was not able to reproduce it.

This worked perfectly! Thanks.
