### ISSUE TITLE
VAAPI not working

### ISSUE THREAD

**Issue by metenn** [flathub/com.github.Eloston.UngoogledChromium#25]
This flatpak supposedly has vaapi support, however, when I enable Hardware Accelerated Decoding in chrome://flags it still doesn't work (checked through intel_gpu_top), and launching through the command line yields the following error messages:
```
Gtk-Message: 02:14:23.099: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:14:23.099: Failed to load module "canberra-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
[42:42:0426/021423.390607:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by metenn** [comment]
`--enable-features=VaapiVideoDecoder --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-gpu-driver-bug-workarounds --enable-accelerated-video-decode --use-gl=desktop`
I tried running these flags in the command line and that seems to fix the issue, however it's not a good permament fix

**Comment by rany2** [comment]
Upstream Chromium doesn't want to support hardware video decode by default. The fact you could enable hardware video decode with these flags means we don't have an issue. Any Chromium will need `--use-gl=desktop`, `--enable-features=VaapiVideoDecoder` and possibly `--ignore-gnu-blocklist` as well.


Until the Chromium devs feel confident enough with hardware decode you'll have to keep doing it that way, though you could put those flags in the `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf` file to load them by default. The file should have a new line between each new option, this is how it should look like:
```
--enable-features=VaapiVideoDecoder
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--disable-gpu-driver-bug-workarounds
--enable-accelerated-video-decode
--use-gl=desktop
```

**Comment by faelana** [comment]
@rany2 what do i need for va api right now? either on wayland or xwayland. i just got it working on firefox.

**Comment by rany2** [comment]
@faelana it works by default for me now, no need to set any flags.

**Comment by rany2** [comment]
@faelana Could you update Ungoogled Chromium to the latest version and show a screenshot of your `chrome://gpu` page?

**Comment by faelana** [comment]
> @faelana Could you update Ungoogled Chromium to the latest version and show a screenshot of your `chrome://gpu` page?

![Screenshot from 2023-08-07 18-56-50](https://github.com/flathub/com.github.Eloston.UngoogledChromium/assets/46012160/27edc738-86f5-4590-9d45-8560bb6d9318)

I also attached a pdf of the full page.
[GPU Internals.pdf](https://github.com/flathub/com.github.Eloston.UngoogledChromium/files/12283769/GPU.Internals.pdf)

**Comment by rany2** [comment]
@faelana I'm not sure, but it does say that it's using hardware video decoding. What makes you think it's not working; I mean, how are you testing whether it is using the GPU for video decoding?
