### ISSUE TITLE
Can't add extensions from path /usr/share

### ISSUE THREAD

**Issue by whygithub9** [flathub/com.github.Eloston.UngoogledChromium#26]
Setting developer mode, then Load unpacked I can't select system wide extensions. This flatpak can't access those installed extensions although I clearly see them inside a file manager such as Nautilus.

I tried `sudo flatpak override com.github.Eloston.UngoogledChromium --filesystem=/usr/share` but it doesn't help.

**Comment by rany2** [comment]
`/usr/share` isn't available in flatpak, it's reserved. You could find it in `/host/usr/share` but that wouldn't work with this flatpak. 

This isn't possible
