### ISSUE TITLE
Use OpenPrinting CUPS

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.github.Eloston.UngoogledChromium#28]
Since Chrome, Edge and Brave have switched to OpenPrinting CUPS, this one should as well.

**Comment by rany2** [comment]
I'll wait until https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml#L67-L77 does the same. I don't want to deviate too much from flatpak Chromium in case some bug pops up
