### ISSUE TITLE
ERR_NO_SUPPORTED_PROXIES even if I don't use a proxy

### ISSUE THREAD

**Issue by Ferenc-** [flathub/com.github.Eloston.UngoogledChromium#29]
```
Flatpak: 1.11.2
OS: Ubuntu 20.04.2 LTS
Kernel: 5.4.0-77-generic
```
I use absolutely no proxy settings.
After roughly 1 minute of  normal operation, suddenly all the http or https sites stop working, with `ERR_NO_SUPPORTED_PROXIES`, and they continue not working until I restart the flatpak app.
  
Other flatpak apps have no network issues, neither has ungoogled-chromium from AppImage.

Some errors are logged:
```
Gtk-Message: 17:13:26.624: Failed to load module "canberra-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
[150:150:0630/171326.687508:ERROR:sandbox_linux.cc(382)] InitializeSandbox() called with multiple threads in process gpu-process.
[110:131:0630/171331.384000:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
Fontconfig error: Cannot load default config file: No such file: (null)
```

From all this time-wise only this message correlates with, the sudden `ERR_NO_SUPPORTED_PROXIES`:
```
Fontconfig error: Cannot load default config file: No such file: (null)
```
The rest of the messages appear even if I don't hit the `ERR_NO_SUPPORTED_PROXIES` issue.

**Comment by rany2** [comment]
Does this happen with `org.chromium.Chromium`?

**Comment by Ferenc-** [comment]
Indeed it does. So I guess this will be an upstream issue.
