### ISSUE TITLE
Unable to install package on Linux Mint due to flatpak version

### ISSUE THREAD

**Issue by japkov** [flathub/com.github.Eloston.UngoogledChromium#33]
Hello!

I'm trying to install the flatpak version of UngoogleChromium on Linux Mint but it seems it requires newest version of flatpak - 1.8.2 while system comes with 1.6.5 and it seems Linux Mint is unable to upgrade the package itself as it's maintained by Ubuntu; and neither flatpak can update itself to newest version.

Is it possible to lower the flatpak version requirement for the browser?

**Comment by rany2** [comment]
Not really, please follow the PPA instructions on https://flatpak.org/setup/Ubuntu/ to install the latest version of Flatpak for Linux Mint.
