### ISSUE TITLE
How to customize or define policy settings？

### ISSUE THREAD

**Issue by LittleboyHarry** [flathub/com.github.Eloston.UngoogledChromium#43]
reference: https://support.google.com/chrome/a/answer/9027408?hl=en&ref_topic=9025817

**Comment by rany2** [comment]
Sorry for the late response but you should reference https://github.com/flathub/org.chromium.Chromium/tree/master/examples/policies/google-safe-search

Simply replace any reference to `org.chromium.Chromium` with `com.github.Eloston.UngoogledChromium` and you should be good.
