### ISSUE TITLE
Hardware Acceleration doesn't work for existing libffmpeg.so

### ISSUE THREAD

**Issue by Motor-head** [flathub/com.github.Eloston.UngoogledChromium#44]
The default `libffmpeg.so` present in version 95.0.4638.54 doesn't use hardware decoding in videos. You have to replace it with [this](https://github.com/Ld-Hagen/fix-opera-linux-ffmpeg-widevine/releases) to actually bring the CPU usage and fan noise down.

**Comment by rany2** [comment]
Most likely an extension of the VAAPI issues.
