### ISSUE TITLE
Chromium can't download anything

### ISSUE THREAD

**Issue by Meister1593** [flathub/com.github.Eloston.UngoogledChromium#47]
It seems that (ungoogled) chromium stopped downloading anything. 
Basically i'm trying to download any file and instead of starting download when i choose where to save through file dialog, it just doesn't do anything.
I'm not sure what caused this because i updated all flatpak packages and it seemed ok (and considering last update was at november 1st for package, i used downloads since that).
I tried making strace on chromium IO inside flatpak shell but to me it looked like a garbage output and didn't make a lot of sense 
So i went here to write issue in case anyone knows what's wrong, how to fix it, or if it's even issue on my side.

System configuration:
OS: Void Linux
Kernel: 5.13.19_1
DE/WM: AwesomeWM
CPU: Ryzen 1600
RAM: 32 GB
Version of chromium: 95.0.4638.69 (Official Build, ungoogled-chromium)
Flatpak version: 1.12.2 (system update was on november 1st too)

**Comment by rany2** [comment]
Hi, I'm not sure what might have gone wrong here but my main thought is that it might be that you don't have xdg-desktop-portal running. Considering this is Void I would think this is likely. 

About 2 months ago, XDG file chooser portal support was added to Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/2992214 and it is switched on by default. Can you verify it is running and try again?

**Comment by Meister1593** [comment]
After rebooting on a next day, it seems to start working. And when i try to force close xdg-desktop-portal (it was running already), it will spawn new instance of xdg-desktop-portal(+gtk) again when download occurs
I think issue may be closed but if it happens again i will investigate it more and re-open issue

**Comment by rany2** [comment]
Thanks!

**Comment by BratSinot** [comment]
Have this problem and don't know what to do (no logs, no messages, nothing!!). Have `xdg-desktop-portal`, `xdg-desktop-portal-kde`, `xdg-desktop-portal-gtk`. Any clue what should i do?
```
hacker@BratSinot ~ flatpak run com.github.Eloston.UngoogledChromium
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
[2:157:0129/125839.814495:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
[2:160:0129/125841.574919:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[2:160:0129/125841.574936:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
```
