### ISSUE TITLE
Basic spellcheck not working

### ISSUE THREAD

**Issue by btcmaine** [flathub/com.github.Eloston.UngoogledChromium#48]
Version 95.0.4638.69 (Official Build, ungoogled-chromium) (64-bit)
flatpak on debian 11

Does not work on any page or with any disctionary. Does not work in incognito or fresh browser profile.

![image](https://user-images.githubusercontent.com/81373393/141229168-1c4d182e-f995-4715-9340-44c03a881477.png)

**Comment by rany2** [comment]
Reopen if that doesn't fix it for you.

https://github.com/flathub/com.github.Eloston.UngoogledChromium#how-do-i-fix-the-spell-checker

**Comment by btcmaine** [comment]
worked perfectly, thanks!

**Comment by rany2** [comment]
no problem, happy to hear! :)
