### ISSUE TITLE
Moving tabs opens a new window in newer version

### ISSUE THREAD

**Issue by Yakui420** [flathub/com.github.Eloston.UngoogledChromium#49]
I'm using debian and version 97.0.4692.71 (flatpak)

Everytime I try to move a tab it just opens another window for me.
Is there a way to fix that?

**Comment by rany2** [comment]
This seems like the same issue as https://github.com/flathub/org.chromium.Chromium/issues/190, so not specific to this chromium.

**Comment by networkException** [comment]
Indeed, see https://github.com/Eloston/ungoogled-chromium/issues/1803

**Comment by rany2** [comment]
@networkException Thanks for this. Happy to know it's not flatpak related either :)

**Comment by networkException** [comment]
Well this could have been fixed in the flatpak release regardless.. `97.0.4692.99-1` will fix it anyways.

**Comment by rany2** [comment]
@networkException Seems like the PR is all good but I'll wait until it gets merged to master
