### ISSUE TITLE
Can't play .mp4 files

### ISSUE THREAD

**Issue by ojoeth** [flathub/com.github.Eloston.UngoogledChromium#5]
When I try to play a (h264) mp4 file it stutters like crazy then says "The video playback was aborted due to a corruption problem or because the video used features your browser did not support." after approximately 1 second.

**Comment by rany2** [comment]
I can't reproduce. Can you share the mp4 link? 

I was able to play https://ftp.fau.de/fosdem/2020/K.3.401/retro_devroom_welcome.mp4 fine, maybe the latest version fixed the issue?

**Comment by ojoeth** [comment]
> I can't reproduce. Can you share the mp4 link?
> 
> I was able to play https://ftp.fau.de/fosdem/2020/K.3.401/retro_devroom_welcome.mp4 fine, maybe the latest version fixed the issue?

It seems it is fixed in the latest version
