### ISSUE TITLE
ERR_NO_SUPPORTED_PROXIES after a few seconds

### ISSUE THREAD

**Issue by spiralw** [flathub/com.github.Eloston.UngoogledChromium#51]
after a few seconds (up to a minute) of having chromium open, every request fails with net::ERR_NO_SUPPORTED_PROXIES until I restart the browser. I don't have any proxy configs set up.

environment: Flatpak 1.11.3, ungoogled-chromium 97.0.4692.99, KDE Neon on kernel 5.11.0-46-generic

**Comment by Ferenc-** [comment]
The last time I have seen that ( #29 ), it appeard to be an upstream issue.  
So it is advised to check if the problem happens with the normal `org.chromium.Chromium˙ as well.

**Comment by spiralw** [comment]
It does. I will report upstream

**Comment by molny** [comment]
I can also approve this issue.
ENV: Flatpak 1.12.4, ungoogled-chromium 98.0.4758.80, KDE Neon on kernel 5.13.0-28-generic

**Comment by rany2** [comment]
Is this still relevant?

**Comment by spiralw** [comment]
Probably not

**Comment by galkinvv** [comment]
I fixed this problem on ubuntu 20.04 by updating xdg-desktop-portal to version 1.8.1-1~flatpak1~20.04

see https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal/+bug/1951685 for details

**Comment by gollum-z** [comment]
Hi,
the problem occurs again with `Flatpak 1.14.4`

Installed version `com.github.Eloston.UngoogledChromium 114.0.5735.106`
OS: `Ubuntu 20.04.6 LTS (Focal Fossa)`
Desktop: `Gnome 3.36.9`

I will report this on [https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal/+bug/1951685](url)
