### ISSUE TITLE
Initial page load very slow on Fedora?

### ISSUE THREAD

**Issue by qpwo** [flathub/com.github.Eloston.UngoogledChromium#52]
I don't think I had this problem with the non-flatpak version. Any ideas how I can speed it up?

I ran a speed test and the speed gets up to normal, just initial page loads are very slow.

**Comment by networkException** [comment]
Could you look in the networking tab whats taking time perhaps?

**Comment by qpwo** [comment]
Sorry for slow response. I set up vanilla firefox and flathub chromium side by side and recorded both with network inspector. Issue seems to have vanished, or was never there. Maybe I needed a system restart, or maybe  I was loading pages in chromium first, then trying firefox, and getting a cached result... In any case, I don't think there's anything to worry about.
