### ISSUE TITLE
using `fallback-x11`

### ISSUE THREAD

**Issue by okias** [flathub/com.github.Eloston.UngoogledChromium#54]
I haven't found any mentioning of replacing x11 socket with [`fallback-x11`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html), does have Chromium some specific requirement for X11 (webrtc or something?)

**Comment by rany2** [comment]
`fallback-x11` wouldn't work because Chromium requires additional flags for Wayland to be enabled. So in the event that Wayland is available flatpak would have allowed Wayland but the app would still be attempting to use X11.

**Comment by okias** [comment]
I see that Chromium flatpak is compiled with Ozone support, could it be done also for Ungoogled Chromium?

**Comment by TheEvilSkeleton** [comment]
It already has Ozone support. You have to run ungoogled-chromium with `--enable-features=UseOzonePlatform --ozone-platform=wayland` by running `flatpak run com.github.Eloston.UngoogledChromium --enable-features=UseOzonePlatform --ozone-platform=wayland` in the terminal or by typing:

```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

In `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf`
