### ISSUE TITLE
U2F/FIDO2 not working

### ISSUE THREAD

**Issue by ojoeth** [flathub/com.github.Eloston.UngoogledChromium#6]
Chromium does not detect FIDO2/U2F USB 2FA keys when plugged in. This is definitely possible in Flatpak as firefox has made it work.

**Comment by buchwasa** [comment]
You can use flatseal to enable this as a temporary workaround or over command line you can run `--socket=pcsc`

**Comment by ojoeth** [comment]
> You can use flatseal to enable this as a temporary workaround or over command line you can run `--socket=pcsc`

I tried this but it still fails to recognise my u2f key

**Comment by buchwasa** [comment]
Do you have pcscd enabled?

**Comment by buchwasa** [comment]
After some more digging, I noticed that the maintainer of Chrome and Chromium also does not have pcsc working, same case here. Will do more digging to see on implementing that here

**Comment by rany2** [comment]
I don't have U2F/FIDO2 to test this but could anyone check if this works now (with `--socket=pcsc` allowed)?

**Comment by rany2** [comment]
Closing.... Feel free to reopen if it's still an issue
