### ISSUE TITLE
Ungoogled Chromium shadows Chromium in GNOME software

### ISSUE THREAD

**Issue by 1player** [flathub/com.github.Eloston.UngoogledChromium#63]
Both Chromium and this application are listed on Flathub, yet due to both sharing the same .desktop file in appstream, this applications shadows Chromium and it is not possible to install the regular version of Chromium through GNOME software.

Upstream says it's a ungoogled-chromium issue and this app should use a different .desktop file to avoid the problem: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1757

See also: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1794

**Comment by rany2** [comment]
It's not a problem. I believe this line https://github.com/flathub/com.github.Eloston.UngoogledChromium/blob/master/com.github.Eloston.UngoogledChromium.desktop#L119 is the culprit.

Both Ungoogled Chromium and Chromium would install themselves as the same .desktop file (at least it's the case with the RPMFusion package). I will remove it as it is causing problems
