### ISSUE TITLE
No hardware acceleration on Wayland

### ISSUE THREAD

**Issue by Motor-head** [flathub/com.github.Eloston.UngoogledChromium#64]
Trying to get Hardware video acceleration on flatpak version of Ungoogled Chromium.
Running on Ubuntu 22.04 with AMDGPU, UnChromium version is 103.0.5060.53.
Tried these flags:

```
--enable-features=VaapiVideoDecoder
--disable-features=UseChromeOSDirectVideoDecoder
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--canvas-oop-rasterization
--ozone-platform=wayland
```

`VDAVideoDecoder` fails to initialize and browser falls back to `VpxVideoDecoder` or `Da1dVideoDecoder`.

[This](https://aur.archlinux.org/cgit/aur.git/tree/ozone-add-va-api-support-to-wayland.patch?h=ungoogled-chromium) patch adds functionality to utilize Ozone VA-API in UnChromium on Wayland. Kindly add this patch if it isn't done already.

**Comment by rany2** [comment]
@networkException What's the status of the patches in the AUR package? What is preventing it from being inside Ungoogled itself? The patch seems shoddy

**Comment by TheEvilSkeleton** [comment]
We might want to contact the author of the patch.

**Comment by networkException** [comment]
It doesn't fit *that* well with the project objectives but I'd still consider it

**Comment by rany2** [comment]
With https://github.com/flathub/com.github.Eloston.UngoogledChromium/pull/76 this would be closed

**Comment by rany2** [comment]
Done, allow a few hours for the update to become available.
