### ISSUE TITLE
The program crushes after a minute or less

### ISSUE THREAD

**Issue by GabiBCN** [flathub/com.github.Eloston.UngoogledChromium#66]
The program crushes after a minute or less on Arch Linux, KDE Plasma (both X11 and Wayland) no matter what I do, whether I change the configuration, watch a video or just open it. It just closes the window.
I'm on the stable branch, 103.0.5060.134
It always happens on my least powerful laptop, but not on the other one. Here is my computer model:

https://www.amazon.es/Acer-Chromebook-CB3-431-pulgadas-Google/dp/B01D1WMB7I
(A corebooted ex-Chromebook that behaves like a normal laptop and doesn't have any problem apart from being a little slow)

And my `neofetch` output:

```
             `ooo/                   OS: Arch Linux x86_64 
            `+oooo:                  Host: Edgar 1.0 
           `+oooooo:                 Kernel: 5.18.14-arch1-1 
           -+oooooo+:                Uptime: 16 mins 
         `/:-:++oooo+:               Packages: 855 (pacman), 7 (flatpak) 
        `/++++/+++++++:              Shell: bash 5.1.16 
       `/++++++++++++++:             Resolution: 1366x768 
      `/+++ooooooooooooo/`           DE: Plasma 5.25.3 
     ./ooosssso++osssssso+`          WM: kwin 
    .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3] 
   -osssssso.      :ssssssso.        Icons: Papirus-Light [Plasma], Papirus-Light [GTK2/3] 
  :osssssss/        osssso+++.       Terminal: konsole 
 /ossssssss/        +ssssooo/-       CPU: Intel Celeron N3060 (2) @ 2.480GHz 

/ossssso+/:- -:/+osssso+- GPU: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx+sso+:-.-/+oso: Memory: 818MiB / 3870MiB
```

**Comment by rany2** [comment]
I forgot to look into this but now that I've noticed it, I've decided to make some research.

First, according to https://en.wikichip.org/wiki/intel/celeron/n3060 that CPU doesn't support AVX and I'm _somewhat_ sure that this package is compiled for CPUs with AVX support. 

I'm thinking, could you provide me with some logs leading up to the crash? I'm particularly curious about the return code and the last line in the command line output. (I think if this was the case, the last line should be something like "Illegal instruction" )

**Comment by rany2** [comment]
Closing due to no reply
