### ISSUE TITLE
Doesnt work through proxy.

### ISSUE THREAD

**Issue by n3thshan** [flathub/com.github.Eloston.UngoogledChromium#67]
I tried with proxy but not working. Pls refer attachments.

proxy gsettings in sanboxed environment:
![Screenshot from 2022-08-02 22-31-57](https://user-images.githubusercontent.com/97467958/182435004-312e07d2-f02e-4dea-a98c-abf3ef215435.png)

Error i get:
![Screenshot from 2022-08-02 22-47-47](https://user-images.githubusercontent.com/97467958/182435215-6fd92d20-f661-4922-8270-c870deb432d2.png)

**Comment by rany2** [comment]
Does it happen with `org.chromium.Chromium`?

**Comment by rany2** [comment]
Closing, reopen if still relevant in the latest version.
