### ISSUE TITLE
native messaging portal not working in flatpak - keepassxc plugin not working

### ISSUE THREAD

**Issue by chymian** [flathub/com.github.Eloston.UngoogledChromium#68]
since there is no debian package on OBS available, I had to use the flatpak on bullseye with the effect, that the keepassxc plugin is not working. see also bug https://github.com/keepassxreboot/keepassxc/issues/8410.
this is a show-stopper.

**Comment by rany2** [comment]
You could allow access to the host to workaround it and also copy + modify the keepass manifest quite a bit. Should be easy to fix.

Note: allowing access to host means the flatpak would have full filesystem access, but it wouldn't be too different from using the deb package or any other traditional package for ungoogled-chromium.
