### ISSUE TITLE
Add missing doh patch from ungoogled-chromium

### ISSUE THREAD

**Issue by tankaras** [flathub/com.github.Eloston.UngoogledChromium#71]
Would be nice to have

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/core/ungoogled-chromium/doh-changes.patch

**Comment by rany2** [comment]
I'm not sure what you mean. All these patches are applied.

**Comment by tankaras** [comment]
Oh my bad. I thought the patch was reponsible for why 'Use secure DNS with custom' was not working. Turns out this feature is broken even on the main project. Sorry.
