### ISSUE TITLE
Where to put policies.json?

### ISSUE THREAD

**Issue by gcd445** [flathub/com.github.Eloston.UngoogledChromium#74]
Where to put policies.json?

I put it on /var/lib/flatpak/app/com.github.Eloston.UngoogledChromium/current/active/files/chromium/policies/managed/policies.json
before, but after an update, the policy is gone so created a new one, but it is not working anymore

**Comment by rany2** [comment]
You could do so by creating a policy extension, try adapting the example in https://github.com/flathub/com.github.Eloston.UngoogledChromium/branch/example-policy
