### ISSUE TITLE
Force dark theme

### ISSUE THREAD

**Issue by pashinskikh** [flathub/com.github.Eloston.UngoogledChromium#8]
Is there a way to enable dark theme on flatpak version of Ungoogled Chromium?

For the version from RPM Fusion I used two flags ("--force-dark-mode" and "--enable-features=WebUIDarkMode") in /usr/bin/chromium-browser-privacy.

**Comment by rany2** [comment]
Yes, those flags would work with this flatpak too!

**Comment by rany2** [comment]
@pashinskikh If you're asking for a good way to do this, you'd create a file with full path `~/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf` and the contents of this should be:
```
--force-dark-mode
--enable-features=WebUIDarkMode
```

**Comment by pashinskikh** [comment]
Thanks a lot, @rany2!
