### ISSUE TITLE
ublock origin causes pages to never load

### ISSUE THREAD

**Issue by amsamam** [flathub/com.github.Eloston.UngoogledChromium#89]
Pop!_OS 22.04 LTS 
Chromium Version 108.0.5359.124
uBlock Origin 1.46.0

This has happened in the past on the debian binaries so probably a related issue. Disabling ublock makes the browser work normally.

**Comment by rany2** [comment]
Please create an issue in https://github.com/ungoogled-software/ungoogled-chromium with more details.
