### ISSUE TITLE
[Ozone+HiDPI] Mouse cursor is tiny

### ISSUE THREAD

**Issue by xduugu** [flathub/com.github.Eloston.UngoogledChromium#94]
I observe the same issue with the tiny cursor as reported for brave (https://github.com/flathub/com.brave.Browser/issues/284). Setting the XCURSOR_PATH as you did in https://github.com/flathub/com.brave.Browser/pull/286 works for ungoogled chromium as well. Could you please apply the same fix to this flatpak? Thanks!

**Comment by rany2** [comment]
Done, will take roughly 4 hours for the change to propagate to the Flathub servers.

**Comment by xduugu** [comment]
Works as expected. Thanks a lot for finding the fix!
